Repository Azure/autorest.csharp, pull requests merged in 2022-07, with the labels that each got.

#2409 Add tests to validate the generated authentication functions
  eng/Generate.ps1
  src/AutoRest.CSharp/Properties/launchSettings.json
  test/AutoRest.TestServerLowLevel.Tests/security-aad.cs
  test/AutoRest.TestServerLowLevel.Tests/security-key.cs
  test/TestServerProjectsLowLevel/security-aad/AutorestSecurityAadClient.cs
  test/TestServerProjectsLowLevel/security-aad/Generated/AutorestSecurityAadClient.cs
  test/TestServerProjectsLowLevel/security-aad/Generated/AutorestSecurityAadClientOptions.cs
  test/TestServerProjectsLowLevel/security-aad/Generated/CodeModel.yaml
  test/TestServerProjectsLowLevel/security-aad/Generated/Configuration.json
  test/TestServerProjectsLowLevel/security-aad/security_aad_LowLevel.csproj
  test/TestServerProjectsLowLevel/security-key/Generated/AutorestSecurityKeyClient.cs
  test/TestServerProjectsLowLevel/security-key/Generated/AutorestSecurityKeyClientOptions.cs
  test/TestServerProjectsLowLevel/security-key/Generated/CodeModel.yaml
  test/TestServerProjectsLowLevel/security-key/Generated/Configuration.json
  test/TestServerProjectsLowLevel/security-key/security_key_LowLevel.csproj
Labels: LLC

#2413 fix(dpg): `ClientOptions.ServiceVersion` should be pascal case
  samples/Azure.AI.DocumentTranslation/Generated/DocumentTranslationClientOptions.cs
  samples/Azure.Analytics.Purview.Account/Generated/PurviewAccountsClientOptions.cs
  samples/CognitiveServices.TextAnalytics/Generated/CognitiveServicesTextAnalyticsClientOptions.cs
  src/AutoRest.CSharp/Common/Output/Models/Types/ClientOptionsTypeProvider.cs
  test/AutoRest.TestServer.Tests/Common/Output/Models/Types/ClientOptionsTypeProviderTests.cs
  test/TestProjects/BodyAndPath-LowLevel/Generated/BodyAndPathClientOptions.cs
  test/TestServerProjects/azure-special-properties/Generated/AutoRestAzureSpecialParametersTestClientOptions.cs
  test/TestServerProjects/media_types/Generated/MediaTypesClientOptions.cs
  test/TestServerProjects/non-string-enum/Generated/NonStringEnumsClientOptions.cs
  test/TestServerProjects/subscriptionId-apiVersion/Generated/MicrosoftAzureTestUrlClientOptions.cs
  test/TestServerProjectsLowLevel/media_types/Generated/MediaTypesClientOptions.cs
  test/TestServerProjectsLowLevel/security-aad/Generated/AutorestSecurityAadClientOptions.cs
  test/TestServerProjectsLowLevel/security-key/Generated/AutorestSecurityKeyClientOptions.cs
Labels: bug, LLC, DPG/RLC v1.1

#2425 Put swagger summary into comment summary
  samples/AppConfiguration/Generated/AppConfigurationClient.cs
  samples/AppConfiguration/Generated/AppConfigurationRestClient.cs
  samples/Azure.AI.DocumentTranslation/Generated/DocumentTranslationClient.cs
  samples/Azure.AI.FormRecognizer/Generated/AzureAIFormRecognizerRestClient.cs
  samples/CognitiveServices.TextAnalytics/Generated/CognitiveServicesTextAnalyticsClient.cs
  samples/CognitiveServices.TextAnalytics/Generated/CognitiveServicesTextAnalyticsRestClient.cs
  src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.cs
  src/AutoRest.CSharp/Common/Generation/Writers/RestClientWriter.cs
  src/AutoRest.CSharp/Common/Output/Models/ConstructorSignature.cs
  src/AutoRest.CSharp/Common/Output/Models/MethodSignature.cs
  src/AutoRest.CSharp/Common/Output/Models/MethodSignatureBase.cs
  src/AutoRest.CSharp/Common/Output/Models/Requests/RestClientMethod.cs
  src/AutoRest.CSharp/Common/Output/Models/RestClient.cs
  src/AutoRest.CSharp/Common/Output/Models/RestClientBuilder.cs
  src/AutoRest.CSharp/Common/Output/Models/Types/ModelFactoryTypeProvider.cs
  src/AutoRest.CSharp/Common/Output/Models/Types/ObjectTypeConstructor.cs
  src/AutoRest.CSharp/DataPlane/Generation/DataPlaneClientWriter.cs
  src/AutoRest.CSharp/LowLevel/Generation/LowLevelClientWriter.cs
  src/AutoRest.CSharp/LowLevel/Output/LowLevelClient.cs
  src/AutoRest.CSharp/Mgmt/Generation/MgmtClientBaseWriter.cs
  src/AutoRest.CSharp/Mgmt/Generation/MgmtRestClientWriter.cs
  src/AutoRest.CSharp/Mgmt/Models/MgmtClientOperation.cs
  src/AutoRest.CSharp/Mgmt/Output/MgmtExtensionClient.cs
  src/AutoRest.CSharp/Mgmt/Output/MgmtTypeProvider.cs
  src/AutoRest.CSharp/Mgmt/Output/OperationSource.cs
  src/AutoRest.CSharp/Mgmt/Output/Resource.cs
  src/AutoRest.CSharp/Mgmt/Output/ResourceCollection.cs
  src/AutoRest.CSharp/MgmtTest/Models/MockTestCase.cs
  src/AutoRest.CSharp/MgmtTest/Output/Mock/MgmtMockTestProvider.cs
  test/AutoRest.TestServer.Tests/Infrastructure/TestServerV1.cs
  test/TestProjects/BodyAndPath-LowLevel/Generated/BodyAndPathClient.cs
  test/TestServerProjects/body-datetime/Generated/DatetimeClient.cs
  test/TestServerProjects/body-datetime/Generated/DatetimeRestClient.cs
  test/TestServerProjects/body-formdata-urlencoded/Generated/FormdataurlencodedClient.cs
  test/TestServerProjects/body-formdata-urlencoded/Generated/FormdataurlencodedRestClient.cs
  test/TestServerProjects/constants/Generated/ContantsClient.cs
  test/TestServerProjects/constants/Generated/ContantsRestClient.cs
  test/TestServerProjects/url/Generated/PathsClient.cs
  test/TestServerProjects/url/Generated/PathsRestClient.cs
  test/TestServerProjectsLowLevel/url/Generated/PathsClient.cs
Labels: LLC, DPG/RLC v1.1

#2446 DPG CADL Emitter
  .gitignore
  src/CADL.Extension/Emitter.Csharp/.eslintrc.cjs
  src/CADL.Extension/Emitter.Csharp/.prettierrc
  src/CADL.Extension/Emitter.Csharp/package-lock.json
  src/CADL.Extension/Emitter.Csharp/package.json
  src/CADL.Extension/Emitter.Csharp/samples/petStore/Generated/cadl.json
  src/CADL.Extension/Emitter.Csharp/samples/petStore/Generated/cadl.yaml
  src/CADL.Extension/Emitter.Csharp/samples/petStore/decorators.js
  src/CADL.Extension/Emitter.Csharp/samples/petStore/petstore.cadl
  src/CADL.Extension/Emitter.Csharp/src/emitter.ts
  src/CADL.Extension/Emitter.Csharp/src/index.ts
  src/CADL.Extension/Emitter.Csharp/src/lib/cadlServer.ts
  src/CADL.Extension/Emitter.Csharp/src/lib/decorators.ts
  src/CADL.Extension/Emitter.Csharp/src/lib/model.ts
  src/CADL.Extension/Emitter.Csharp/src/type/BodyMediaType.ts
  src/CADL.Extension/Emitter.Csharp/src/type/CodeModel.ts
  src/CADL.Extension/Emitter.Csharp/src/type/ExternalDocs.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputClient.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputConstant.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputOperation.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputOperationParameterKind.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputParameter.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputType.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputTypeKind.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputTypeSerializationFormat.ts
  src/CADL.Extension/Emitter.Csharp/src/type/InputTypeValue.ts
  src/CADL.Extension/Emitter.Csharp/src/type/OperationFinalStateVia.ts
  src/CADL.Extension/Emitter.Csharp/src/type/OperationLongRunning.ts
  src/CADL.Extension/Emitter.Csharp/src/type/OperationPaging.ts
  src/CADL.Extension/Emitter.Csharp/src/type/OperationResponse.ts
  src/CADL.Extension/Emitter.Csharp/src/type/Protocols.ts
  src/CADL.Extension/Emitter.Csharp/src/type/RequestLocation.ts
  src/CADL.Extension/Emitter.Csharp/src/type/RequestMethod.ts
  src/CADL.Extension/Emitter.Csharp/src/type/ValidationType.ts
  src/CADL.Extension/Emitter.Csharp/test/TestProjects/endpoint/Generated/cadl.json
  src/CADL.Extension/Emitter.Csharp/test/TestProjects/endpoint/Generated/cadl.yaml
  src/CADL.Extension/Emitter.Csharp/test/TestProjects/endpoint/endpoint.cadl
  src/CADL.Extension/Emitter.Csharp/test/TestProjects/string-format/Generated/cadl.json
  src/CADL.Extension/Emitter.Csharp/test/TestProjects/string-format/Generated/cadl.yaml
  src/CADL.Extension/Emitter.Csharp/test/TestProjects/string-format/string-format.cadl
  src/CADL.Extension/Emitter.Csharp/tsconfig.json
  src/CADL.Extension/codemodel.png
  src/CADL.Extension/flow.png
  src/CADL.Extension/readme.md
Labels: LLC, DPG/RLC August MVP

#2499 Add new `ContentType` format
  docs/mgmt/polishing.md
  src/AutoRest.CSharp/Common/Generation/Types/TypeFactory.cs
  src/AutoRest.CSharp/Common/Generation/Writers/JsonCodeWriterExtensions.cs
  src/AutoRest.CSharp/Common/Input/CodeModelPartials.cs
  src/AutoRest.CSharp/Mgmt/Decorator/ParameterMappingBuilder.cs
  src/AutoRest.CSharp/MgmtTest/Extensions/CodeWriterExtensions.cs
  test/TestProjects/MgmtRenameRules/Generated/CodeModel.yaml
  test/TestProjects/MgmtRenameRules/Generated/Configuration.json
  test/TestProjects/MgmtRenameRules/Generated/Models/AdditionalUnattendContent.Serialization.cs
  test/TestProjects/MgmtRenameRules/Generated/Models/AdditionalUnattendContent.cs
  test/TestProjects/MgmtRenameRules/MgmtRenameRules.json
  test/TestProjects/MgmtRenameRules/readme.md
Labels: v3, Mgmt

#2512 [CODEOWNERS] Unify files and update owners
  .github/CODEOWNERS
Labels: EngSys, Client

#2517 [CODEOWNERS] Remove duplicate file
  CODEOWNERS
Labels: EngSys, Client
