Repository Azure/autorest.csharp, pull requests merged in 2023-03, with the labels that each got.

#3149 a minor refactor on mgmt plane code
  src/AutoRest.CSharp/Mgmt/Generation/MgmtClientBaseWriter.cs
Labels: Mgmt

#3195 Convert to type object for body parameter only
  src/AutoRest.CSharp/LowLevel/Output/OperationMethodChainBuilder.cs
  test/TestProjects/CollectionFormat-Cadl/CollectionFormat-Cadl.cadl
  test/TestProjects/CollectionFormat-Cadl/Generated/ArrayAsQueryOrHeaderClient.cs
  test/TestProjects/CollectionFormat-Cadl/Generated/Models/Thing.Serialization.cs
  test/TestProjects/CollectionFormat-Cadl/Generated/Models/Thing.cs
  test/TestProjects/CollectionFormat-Cadl/Generated/cadl.json
Labels: DPG

#3157 change things depending on my own properties in lowlevelclients into lazy loading pattern
  src/AutoRest.CSharp/LowLevel/Output/LowLevelClient.cs
Labels: DPG

#3162 Simplify the generation script
  eng/Generate.ps1
  eng/Generation.psm1
  eng/testProjects.json
  samples/AnomalyDetector/tspconfig.yaml
  test/CadlRanchProjects/arrays/item-types/tspconfig.yaml
  test/CadlRanchProjects/authentication/api-key/tspconfig.yaml
  test/CadlRanchProjects/authentication/oauth2/tspconfig.yaml
  test/CadlRanchProjects/authentication/union/tspconfig.yaml
  test/CadlRanchProjects/enums/extensible/tspconfig.yaml
  test/CadlRanchProjects/hello/tspconfig.yaml
  test/CadlRanchProjects/models/property-optional/Generated/Configuration.json
  test/CadlRanchProjects/models/property-types/tspconfig.yaml
  test/CadlRanchProjects/models/usage/tspconfig.yaml
  test/CadlRanchProjects/projection/tspconfig.yaml
  test/TestProjects/ApiVersion-Typespec/tspconfig.yaml
  test/TestProjects/Authoring-Typespec/tspconfig.yaml
  test/TestProjects/ClientAndOperationGroup-Typespec/tspconfig.yaml
  test/TestProjects/CollectionFormat-Typespec/tspconfig.yaml
  test/TestProjects/Customizations-Typespec/tspconfig.yaml
  test/TestProjects/FirstTest-Typespec/tspconfig.yaml
  test/TestProjects/Lro-Basic-Typespec/tspconfig.yaml
  test/TestProjects/MediaTypes-Typespec/tspconfig.yaml
  test/TestProjects/MixAPIVersion-Typespec/tspconfig.yaml
  test/TestProjects/Models-Typespec/tspconfig.yaml
  test/TestProjects/Pagination-Typespec/tspconfig.yaml
  test/TestProjects/Parameters-Typespec/tspconfig.yaml
  test/TestProjects/PetStore-Typespec/tspconfig.yaml
  test/TestProjects/RenameGetList-Typespec/tspconfig.yaml
  test/TestProjects/Spread-Typespec/tspconfig.yaml
Labels: DPG

#3171 Add pipeline to generate valid SDK change against WIP codegen change
  eng/BuildPRUrl.ps1
  eng/GenerateInternalNpmrc.ps1
  eng/PackArtifacts.ps1
  eng/PackEmitter.ps1
  eng/UpdateAzureSdkForNet.ps1
  eng/UpdateGeneratorMetadata.ps1
  eng/pipelines/build.yml
  eng/pipelines/sdk-update.yml
  eng/pipelines/update-azure-sdk-for-net-codes.yml
  eng/pipelines/update-generator-versions.yml
Labels: Mgmt, Do Not Merge, DPG

#3220 upgrade typespec to 0.42.0
  package-lock.json
  src/CADL.Extension/Emitter.Csharp/package.json
  test/CadlRanchMockApis/package.json
Labels: DPG

#3227 update emitter readme
  src/CADL.Extension/Emitter.Csharp/package.json
  src/CADL.Extension/readme.md
Labels: DPG

#3226 add collectionFormat test in cadl-ranch
  eng/testProjects.json
  src/AutoRest.CSharp/Properties/launchSettings.json
  test/CadlRanchMockApis/src/CollectionFormat-Cadl.ts
  test/CadlRanchProjects.Tests/CollectionFormat.cs
  test/CadlRanchProjects/collectionFormat/Generated/CollectionFormatClient.cs
  test/CadlRanchProjects/collectionFormat/Generated/CollectionFormatClientBuilderExtensions.cs
  test/CadlRanchProjects/collectionFormat/Generated/CollectionFormatClientOptions.cs
  test/CadlRanchProjects/collectionFormat/Generated/Configuration.json
  test/CadlRanchProjects/collectionFormat/Generated/Docs/CollectionFormatClient.xml
  test/CadlRanchProjects/collectionFormat/Generated/Models/MessageResponse.Serialization.cs
  test/CadlRanchProjects/collectionFormat/Generated/Models/MessageResponse.cs
  test/CadlRanchProjects/collectionFormat/Generated/cadl.json
  test/CadlRanchProjects/collectionFormat/collectionFormat.csproj
  test/TestProjects/CollectionFormat-Typespec/CollectionFormat-Typespec.tsp
  test/TestProjects/CollectionFormat-Typespec/Generated/ArrayAsQueryOrHeaderClient.cs
  test/TestProjects/CollectionFormat-Typespec/Generated/ArrayAsQueryOrHeaderClientBuilderExtensions.cs
  test/TestProjects/CollectionFormat-Typespec/Generated/ArrayAsQueryOrHeaderClientOptions.cs
  test/TestProjects/CollectionFormat-Typespec/Generated/Docs/ArrayAsQueryOrHeaderClient.xml
  test/TestProjects/CollectionFormat-Typespec/Generated/Models/Thing.cs
  test/TestProjects/CollectionFormat-Typespec/tspconfig.yaml
Labels: DPG
